### ISSUE TITLE
[Feature Request] Export skill name+dropdown selections to pobsearch

### ISSUE THREAD

**Issue by xanthics** [VolatilePulse/PoB-Item-Tester#1]
Could you add a parameter to the query string that is the selected skill name and any subselections?

EG: "Molten Strike: Magma Balls" or "Pathfinder Molten Strike: Magma Balls"

b_name would be an acceptable parameter name.  That way there is something on the page to indicate what build the stats are for.

**Comment by coldino** [comment]
I'll add the skill name and also include the character name. Both are a useful check to ensure you are testing the right thing...
Example: `Skill=Molten%20Strike%20%2F%20Magma%20Balls&Character=Zivhi`

**Comment by xanthics** [comment]
Excellent.  I'll push an update now to use those two keywords

**Comment by coldino** [comment]
Done in 2fc6b6013de90b1c45e9aacf39e8f647086b567d.

I don't see it appearing on the site yet, but I assume that's just an update thing.
