### ISSUE TITLE
Script is opening dps search with no values.

### ISSUE THREAD

**Issue by codeninja** [VolatilePulse/PoB-Item-Tester#11]
Using POB 1.4.146. 

When I issue the keybind for dps search the script will open the weighted search generator but none of the values are filled in.

![image](https://user-images.githubusercontent.com/14914/61015984-9a6da200-a353-11e9-9035-05c35bb134f1.png)

Note that the other checkbox values are correct... I'm using a wand and shield.

**Comment by VolatilePulse** [comment]
Sorry I didn't get back to you sooner, was a rather late night last night. Can you paste the url that generates the search generator page?

**Comment by VolatilePulse** [comment]
Have you resolved the issue? If not, please make sure you have the latest version of the script. If that still hasn't resolved the the issue, open this issue back up and provide any additional information that may help us track down the issue. Thank you!
