### ISSUE TITLE
Error at line 11 @ TestItem.ahk

### ISSUE THREAD

**Issue by SneakySphynx** [VolatilePulse/PoB-Item-Tester#12]
Line text: global _LuaDir:="\ItemTester"
Error: This line does not contain a recognized action.

The program will exit.

Happens at trying to launch TestItem.Ahk with version v1 of AHK.

**Comment by coldino** [comment]
v1 of AHK is probably a decade old is not supported.

v1.1's most recent release is what you want. See <https://www.autohotkey.com/download/>.

v2 of AHK is not ready despite being in development for nearly a decade. Not supported.

**Comment by SneakySphynx** [comment]
> v1 of AHK is probably a decade old is not supported.
> 
> v1.1's most recent release is what you want. See https://www.autohotkey.com/download/.
> 
> v2 of AHK is not ready despite being in development for nearly a decade. Not supported.

That worked perfectly thanks mate, said v1 in the description so was a bit lost. :)
