### ISSUE TITLE
using script on Windows login produces error

### ISSUE THREAD

**Issue by jnitis** [VolatilePulse/PoB-Item-Tester#13]
With the AHK script in shell:startup on Win10 the script produces the attached error.  Clicking OK makes it go away and the script runs fine in the background, but thought I'd report this as I've been clicking OK for months now. :-)

![test item](https://user-images.githubusercontent.com/5638068/61346822-03f02380-a820-11e9-9795-d580e5f07c8d.jpg)

**Comment by VolatilePulse** [comment]
Here's a modified version for you to try out. Let me know if it solves the issue as I can't seem to get the same results as you. Just unzip it and replace the existing file with this one. Only a couple of lines have been changed.
[TestItem.zip](https://github.com/VolatilePulse/PoB-Item-Tester/files/3402655/TestItem.zip)

**Comment by jnitis** [comment]
Works perfectly, thank you very much!
