### ISSUE TITLE
Item type is not supported

### ISSUE THREAD

**Issue by Vagaqt** [VolatilePulse/PoB-Item-Tester#14]
I'm having difficulties creating an item search. The script starts up, but i get an error message 'Item type is not supported.' when i try to import build from PoB.

**Comment by Vagaqt** [comment]
And today the error message says 'Not a PoE item.'

**Comment by VolatilePulse** [comment]
Sorry for the delayed response, work has been keeping me busy and won't have time until later Sunday to take a better look. Just to make sure, you have saved your PoB builds and have selected the build using the user interface of the item tester? Also, for the item tester to work, it observes the text in your clipboard and checks for valid items. The Readme how a more detailed explanation of the step to step process to get it to work.

**Comment by Vagaqt** [comment]
It was working fine until two days ago, i haven't changed anything

**Comment by Vagaqt** [comment]
It seems to be working fine now, i have no idea what happened.

**Comment by VolatilePulse** [comment]
Oh okay. Out of curiosity, do you use the official trade site or a third party? We test against official, but it may work with other trade sites.
