### ISSUE TITLE
None of the Hotkeys work

### ISSUE THREAD

**Issue by Seleukus** [VolatilePulse/PoB-Item-Tester#16]
Hello, I've used this script in the past a lot, but now this season (Delirium) none of the hotkeys are working.
I've tried cleaning everything up and installing again (PoB updated, autohotkey 1.1 installed, tried v1 as well) but still doesn't work.
When I run the script for the first time, it asks me to run PoB, and then when I do so, it shows UI to pick a build. Nothing else happens afterwards.

I have Windows 10 Pro 64bit, Version 10.0.18362 Build 18362. I have PT keyboard (tried both ENG PT and ENG US language settings in windows).
I know java and git, but I'm unfamiliar with this script language.

Any idea what might be the problem?

**Comment by VolatilePulse** [comment]
The most common issue is that your Windows key is disabled by your keyboard. This is a common feature of gaming keyboards. To test this out quickly, you can press Windows + R on the keyboard and see if it opens the Run... window. If it does, there may be something else going on.

I believe that the AHK script can only be ran with AHK v1.0 and not v1.1. You may also be having issues with antivirus software, but check the other two things first and get back to me. Thanks!

**Comment by Seleukus** [comment]
I randomly smashed all the "gaming" keys (macro/mode/function) which I never used anyway and eventually it started working! ahah I feel like a dumbass
Thank you very much kind sir!

**Comment by VolatilePulse** [comment]
That's great! 

For others that may be struggling; many gaming keyboards do have a toggle for the "feature" typically found in the software for the keyboard while other ones, by default, disable the Windows key when the keyboard is put into "gaming" mode. Gaming mode is some times set by a toggle on the keyboard, while others may have specific keys that turn it on and off.

We always recommend you check your keyboards manual or contact the manufacturer if you have further questions.
