### ISSUE TITLE
Not generating a link to the official trading site.

### ISSUE THREAD

**Issue by nikoooobellliiicc** [VolatilePulse/PoB-Item-Tester#17]

**Comment by nikoooobellliiicc** [comment]
The 'Search Generated mods' does not create a link to the official trading site PoE uses. It does create another tab in my browser, but with the exact same link as the one i clicked the button in.
The URL provided does seem to create some kind of weighted search; 

https://xanthics.github.io/PoE_Weighted_Search/?flataccuracy=4300.2&paccuracy=1424.6&pphysical=149.9&plightning=1083.1&pcold=1283.7&pelemental=1317.0&pchaos=60.1&pgeneric=1466.8&pspell=2188.0&pattack=1466.8&critchance=1251.3&critmulti=4547.5&basecrit=3941.5&attackspeed=4337.2&penall=5374.1&penlightning=177.9&pencold=5196.2&flatphys=765.5&flatlightning=9593.6&flatcold=5210.9&flatfire=4910.3&flatchaos=580.8&chancedoubledamage=954.2&extralightning=2964.9&extracold=2649.2&extrafire=2033.0&extrachaos=19299.8&eleaschaos=18081.8&physicalasextrachaos=1215.7&lightningasextrachaos=8340.5&coldasextrachaos=9746.2&20dex=1424.6&damageperdex=1212.5&damageperint=3651.9&damageperstr=1331.0&pdex=1424.6&plife=245.5&pmana=245.5&aspellsg=3852.4&FrenzyCount=0&PowerCount=0&EnduranceCount=0&Flags=OneHandedWeapon,Wand,conditionLowLife,Attack,Projectile,multiplierKilledRecently,conditionHaveEnergyShield,DualWielding,multiplierMinionsKilledRecently,minionsUseFrenzyCharges,minionsConditionFullLife,conditionHitRecently,&Skill=Kinetic%20Bolt&Character=kinetic%20bolt%20slingert

Would love to have some support, since this tool really does look amazing ;)

**Comment by xanthics** [comment]
Works fine for me?

caster weapon https://www.pathofexile.com/trade/search/Delirium/nwMBrP9u0
base jewel https://www.pathofexile.com/trade/search/Delirium/YyL8yr6iY

Can you press f12(dev console) go to the console tab, and then try using my site?

**Comment by nikoooobellliiicc** [comment]
![image](https://user-images.githubusercontent.com/63198231/78516207-0e40bc00-77b9-11ea-822b-fec8eb20e8cc.png)

This is what it shows if i try to use your site. It might surely be a mistake on my end but i'm really unaware of the mistake im making. Thanks in advance for support!

**Comment by xanthics** [comment]
Looks like you might be blocking Brython?  This is my console log

![image](https://user-images.githubusercontent.com/3137623/78533205-741f4a80-779d-11ea-86de-4e55eb4b22fa.png)

Go to the network tab, type .js in the search and then reload

![image](https://user-images.githubusercontent.com/3137623/78533341-a9c43380-779d-11ea-8a3d-3631036aa7a1.png)

**Comment by nikoooobellliiicc** [comment]
This is what it shows when i type in .js and reload. Any clue how to solve this? I'm not too familiar with troubleshooting this tbh. Thanks a bunch in advance!

![image](https://user-images.githubusercontent.com/63198231/78551902-c8aae000-7806-11ea-872e-ebbea94be3ec.png)

**Comment by nikoooobellliiicc** [comment]
Ah I've been browsing some threads and it appears firefox was having issues fetching the api, when I try it on chrome it does work, so i'll be using that from now on ;) Thanks for helping friend!
