### ISSUE TITLE
Physical DoT Multiplier

### ISSUE THREAD

**Issue by omgbbqmark** [VolatilePulse/PoB-Item-Tester#19]
The tool generates a weight for Physical Damage over Time Multiplier, but the weight does not get output to the query string/trade site.  This may be because it is called generically "Damage over Time multiplier" in the tool, but "Physical Damage over Time Multiplier" in-game now.

**Comment by xanthics** [comment]
Damage over Time and Phys Damage over Time are separate mods, with Phys being a subset of the other.  I've added the mod to my site and updated the json for this project.

57414d875d058aa2a664c288488db25f2d2119d2

xanthics/PoE_Weighted_Search@d4da0441d68a8e0dcc5e8b3521f9031afb41de5a
