### ISSUE TITLE
TestItem.ahk only sees xml files in root of Builds

### ISSUE THREAD

**Issue by xanthics** [VolatilePulse/PoB-Item-Tester#2]
When looking for builds to enumerate, the ahk script only considers the root Builds directory.  I use sub folders to organize builds, usually by major release number or currency cost.  No error is given to indicate this behavior.

**Comment by VolatilePulse** [comment]
Thanks! Already aware of it, even have a comment in the code specifically referring to this limitation. I'll be away from my PC for a few days so I won't be able to fix this right away, but it'll be on my list for when I get back. I'll fix it in 2 steps.

To get it working, the first fix will support all subdirectories but will display all build paths in the list box (including the directories) which means more scrolling.

Once I figure out a good way to implement navigating the directories, I'll switch it so you can navigate the directories within the window with the current directory displayed.
