### ISSUE TITLE
question, how does this work with non-portable PoB which doesn't include Launch.lua

### ISSUE THREAD

**Issue by mahhov** [VolatilePulse/PoB-Item-Tester#20]
Firstly, thanks, this repo helped tremendously in figuring out how to integrate with PoB, especially since I have no Lua experience.

I see the readme mentions:
> supports both the portable and installer versions

For my app, I'm able to get integration with the portable version working.
But the installer version, which doesn't include `Launch.lua` doesn't work:
> cannot open Launch.lua: No such file or directory
> ...
> HeadlessWrapper.lua:171 // [dofile("Launch.lua")](https://github.com/Openarl/PathOfBuilding/blob/master/HeadlessWrapper.lua#L167)

I see you're using mockui.lua in lieu of HeadlessWrapper.lua, but that too has a `dofile("Launch.lua")` on [line 214](https://github.com/VolatilePulse/PoB-Item-Tester/blob/master/ItemTester/mockui.lua#L214).

Could you point me to how you get around this issue?

**Comment by VolatilePulse** [comment]
The readme does include this warning:
```
! Warning: Supports the Community Fork of PoB but only the PORTABLE version until we find a workaround!
```

We do have some instructions for how to "hack" it to work as posted on our Discord. You can try the following steps:
```
1) Unzip the portable .zip version of the fork to a nice simple directory like C:\POBFORK
2) Fire up *that* version of PoB, open Options (bottom right) and set the 'Build save path' to match your installed one
3) Exit PoB-Item-Tester, then go into its install folder and open TestItem.ini in an editor like notepad
4) Change the values for PathToPoB and PathToPoBInstall to point at your portable install folder like C:\POBFORK
5) Make sure the BuildDirectory value is pointing at your builds folder
6) Test it!
```

The installed version worked prior to this change in the community branch and we haven't implemented a working fix yet but this does seem to work properly.

**Comment by mahhov** [comment]
I should have clarified, I'm referring to the non-community fork; i.e. [Openarl's original](https://github.com/Openarl/PathOfBuilding).

**Comment by VolatilePulse** [comment]
That is something that we are not aware of then. The installed version places the LUA files in the Program Data directory instead of the installation directory, but if it's no longer coming with the launch file, it will require further diagnosis. For the time being, we would recommend using the portable version until we've been able to track down the issue.

**Comment by mahhov** [comment]
Interesting. If pob used `require` insted of `dofile` & `loadfile`, then I think all we'd have to do was add both paths (e.g. `C:\ProgramData\Path of Building` & `C:\Program Files (x86)\Path of Building`) to the `package.path` or `LUA_PATH`.
But alas `dofile` & `loadfile` only seem to search the current working dir.

Maybe it's worth putting in a PR to PoB adopting `require`. Altneratively, we could copy the .lua files from both dirs to a temp dir to use as the current working dir.

**Comment by VolatilePulse** [comment]
It was just pointed out to me that you're asking for assistance in your own app, not this app specifically and that you were just curious as to how we were able to support the installed version. I'm sorry for the misunderstanding and I understand that AHK is challenging to read, but as many installed programs use the Program Data directory, that is what we started with and sure enough, PoB is no different.

I believe that we set the current working directory to either the portable directory or the program directory based on which version of PoB is present. I'm not sure that we use any of the data from the installed directory, but for your app, copying the necessary files to a temp directory should achieve what you're looking for.

**Comment by coldino** [comment]
You can check the [test.bat](https://github.com/VolatilePulse/PoB-Item-Tester/blob/master/test.bat) for how we setup the paths. There's a comment saying what to change to for an installed version.

There's no need to change PoB - and certainly there's no way you'll get a change into the original PoB!  I tried for a long time before my changes finally went into the community fork.

**Comment by mahhov** [comment]
Thanks for both of your inputs, very helpful. Using `program data` dir sound good for my needs.
