### ISSUE TITLE
Problem with starting TestItem.ahk

### ISSUE THREAD

**Issue by dejrons** [VolatilePulse/PoB-Item-Tester#24]
![image](https://user-images.githubusercontent.com/59622333/102719340-d0a3a500-42ed-11eb-9ff9-28b9bff6fec4.png)

I've got a problem with starting the ahk script for some time, not sure when this started. I wasn't reinstalling PoB (Fork) meantime. 

PoB Community Fork 1.4.170.20 right now

**Comment by coldino** [comment]
Hopefully you were one of the users that we assisted in Discord.

The current version should be robust with a fresh PoB installation (not just updated but re-installed from a recent download).

If there is still an issue, please re-open.
