### ISSUE TITLE
Pressing "Generate query" does nothing.

### ISSUE THREAD

**Issue by kilpsz** [VolatilePulse/PoB-Item-Tester#25]
Title, tried multiple different searches but still did nothing.

**Comment by skules** [comment]
Same, tried different browsers as well

**Comment by VolatilePulse** [comment]
We have just found this issue for this bug. Since this isn't part of the item tester itself, a fix will have to be released by the DPS Search developer instead. It appears to be an error within the generation code.

For posterity, the error is:
```py
Traceback (most recent call last):
  module __main__ line 48, in generate_query
    querystring, count, culled = gensearchparams(dps, selections, base)
  module gensearchparams line 361, in gensearchparams
                for val in mods[mod]:
KeyError: Spells have #% to Critical Strike Chance 
```

**Comment by VolatilePulse** [comment]
The fix has been released. A cache refresh (CTRL + F5) may be required on the DPS Search site to obtain the changes.
