### ISSUE TITLE
webside not opening

### ISSUE THREAD

**Issue by Waldemar-as** [VolatilePulse/PoB-Item-Tester#26]
after i press Ctrl-Windows-Alt-D, pick my build,  nothing happens. the webside https://xanthics.github.io/PoE_Weighted_Search/ wont open.

Ok, it works now somehow.

**Comment by coldino** [comment]
Do you get an error that you could share?

If you don't get an error then you might be using an old version, so please re-download the item tester.

Another thing that might be necessary is to reinstall PoB as a couple of specific versions of its installer have been installing it into the wrong place.

**Comment by coldino** [comment]
Closing as original issue was edited.
