### ISSUE TITLE
ERROR: Don't know how to deal with this build's damage output type

### ISSUE THREAD

**Issue by pattonjh** [VolatilePulse/PoB-Item-Tester#29]
Error as seen in title when attempting to generate weights via Ctrl+Win+D. I am playing SRS with Minion Instability. POB xml file attached.

I am on the latest version of both Community PoB and this repo. The previous version of this repo I had installed did not cause this error.

[SRS-build-XML.txt](https://github.com/VolatilePulse/PoB-Item-Tester/files/6396046/SRS-build-XML.txt)

**Comment by xanthics** [comment]
If you are able, try the dev branch and see if it fixes your issue.  (Not an ahk/lua dev, but there are fixes on that branch to address issues discovered with minions)

**Comment by pattonjh** [comment]
@xanthics Thanks for the heads up. I grabbed the dev branch and it runs without an error. Unfortunately, the page on your side loads with a 0 weight for everything.

I'm not sure if that would be an item tester issue or an issue for your weighted search repo.

**Comment by xanthics** [comment]
The 0 weights is a PoB issue

not FullDPS

![image](https://user-images.githubusercontent.com/3137623/116600034-b00fdb00-a8dd-11eb-992b-98ff241d3a9b.png)

FullDPS (note that all the nodes have a node power of 0, even if they contribute to full dps)

![image](https://user-images.githubusercontent.com/3137623/116600102-c87ff580-a8dd-11eb-8c57-5fd116c16bc4.png)

**Comment by coldino** [comment]
The `Don't know how to deal with this build's damage output type` error for minion builds has been fixed in PoB-Item-Tester (and pushed to the master branch now). Sadly there's not a lot we can do with PoB until the calculator is fixed for these types of builds.

I'll close this issue now as the rest of the work is out of my hands.

**Comment by pattonjh** [comment]
Prior to updating to the latest (master) version of Item Tester, using it on this build generated weights. It missed Minion Life, but it still generated weights for Inc Minion Dmg, Minions deal # to # additional dmg, etc. When I updated to the latest Item Tester, I got the error described in the original comment. When I updated to the dev branch, I get a 0 weight in everything.

I'm definitely not as well-versed in the interactions between PoB, Item Tester, and Weighted-Search - but why would I have been generating weights prior to updating Item Tester if it's a PoB issue?

**Comment by xanthics** [comment]
I can get your build to generate weights if full dps is enabled but not if it is disabled.

![image](https://user-images.githubusercontent.com/3137623/116756180-88de0a00-a9c0-11eb-9dd5-f79b6dddc1fd.png)

https://xanthics.github.io/PoE_Weighted_Search/?vals=3,2086.0,,,2086.0,2001.8,,,2086.0,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,612.1,,1067.3,161.5,189.7,482.8,1375.4,,279.8,1000.5,1215.1,2022.5,133.0,,,,,,,,,,,,,,,,,,,,,,,,60.6,317.4&Flags=OneHandedWeapon,Duration,Wand,Fire,Elemental,EnemyFireExposure,UsedMinionSkillRecently,CreatesMinion,Minion,enemyConditionHitByLightningDamage,Spell,CreateMinion,Shield,&Skill=Summon%20Raging%20Spirit&Character=test%2Dmi
