### ISSUE TITLE
DPS Generator doesn't open a browser window

### ISSUE THREAD

**Issue by Davst** [VolatilePulse/PoB-Item-Tester#30]
Just has a little window that says it is working then nothing happens..

**Comment by coldino** [comment]
Well that's not a lot to go on, but... 

1) Are you using an up-to-date PoB Item Tester? The have been fixed recently to support recent PoB changes.

2) You should uninstall PoB and reinstall from the latest download. There were some odd versions of the installer that we couldn't support even when fully updated.

 3) If none of these work please supply your PoB pastebin so we can look into it.

**Comment by Davst** [comment]
1. Yeah just installed it a few days ago. 
2. Followed your suggestion to reinstall PoB with the latest installer, some progress.. now instead of nothing happening i get the following error..

```
C:\Games\POE Tools\PoB-Item-Tester-master\bin\luajit.exe: ...s\POE Tools\PoB-Item-Tester-master\ItemTester\mockui.lua:233: ERROR: Path of Building must be re-installed using a recent installer.
stack traceback:
	[C]: in function 'error'
	...s\POE Tools\PoB-Item-Tester-master\ItemTester\mockui.lua:233: in main chunk
	[C]: in function 'dofile'
	...OE Tools\PoB-Item-Tester-master\ItemTester\SearchDPS.lua:15: in main chunk
	[C]: at 0x004020f0
```

**Comment by coldino** [comment]
Huh. Can you point me at the exact installer you downloaded? Or at least tell me the filename of it if you still have it in your Downloads folder?

**Comment by coldino** [comment]
Also, there's a chance you have multiple versions of PoB installed. If so you should make sure you uninstall them all before starting from scratch.

**Comment by Davst** [comment]
Still have it. It is the latest release from the github as of yesterday

Sent from a device with a touch keyboard and ”autocorrect”.

**Comment by coldino** [comment]
Had another user on our Discord asking about the same issue and was able to narrow it down with them finally. Seems to be triggered by PoB being in the "Load a build" start screen, so you can workaround it by simply loading a build into PoB and exiting it.

I'll update when I have a proper fix in place.

**Comment by coldino** [comment]
Latest version will hopefully resolve your issue. Please re-open this issue with details if not.
