### ISSUE TITLE
Installation/Requirement question

### ISSUE THREAD

**Issue by Eruyome** [VolatilePulse/PoB-Item-Tester#5]
You're saying that only the zip version works because the installer is missing a file. Can I copy that file (or those files) from the zip archive to my installed PoB or do I have to uninstall PoB, then use the zip?

**Comment by coldino** [comment]
I believe the only file missing is `Launch.lua` so it should be simple to copy this into the installation directory.

Test it out, and if that's not the case I'll look further into it.

**Comment by VolatilePulse** [comment]
There should also be a batch file included in the directory. You're looking for `testdps.bat`. Edit the file, select the correct directory for PoB, and run the batch file from the command line or PowerShell. That should give significantly more information.

I thought I tested the installed version of PoB with the `Launch.lua` file added and it didn't work then, but I had high hopes as some significant changes were made in PoB with this latest round of updates. Depending on the results of the batch file, I'd likely say this script will **only** work with the zip version of PoB. Real shame too, but I believe it would take too much work to get the installation version working properly.

**Comment by Eruyome** [comment]
Yeah it just fails even after copying over all those folders `classes\modules\treedata\data`.

![image](https://user-images.githubusercontent.com/16058242/49931875-1d1aa580-fec8-11e8-855b-17343f3fab4b.png)

I tried replacing the contents of my installed PoB with the zip files contents, same path so that windows still knows where to find it. This also happens when I use a different path where I originially extracted the zip file to.

![image](https://user-images.githubusercontent.com/16058242/49932294-f6a93a00-fec8-11e8-85cd-d616fee679ad.png)

**Comment by coldino** [comment]
Okay. This may be something as simple as the script not handling spaces in your paths well. I'll try and replicate the issue locally.

**Comment by VolatilePulse** [comment]
Wanted to report back. We have been actively looking into the issues with the installed version of PoB. It appears all of the necessary Lua script files are actually installed along with PoB. But we are experiencing issues with the files being split across multiple directories. Once we figure something more out, we will be sure to update you and hopefully the script to fully support all versions of PoB or officially rule out support for the installer version. Thank you for your patience while we look into this further.

**Comment by VolatilePulse** [comment]
As a quick follow up, we have managed to get the script to work on an Installed version of PoB and will be working towards supporting it in an upcoming commit. I'm hoping I can get most, if not all, of it done and committed this evening. It would require no additional user interaction, but may require some additional testing to verify it works as expected.

**Comment by VolatilePulse** [comment]
Solved with 5d112a1753305afba9e9345b8f1528bc0

This should enable full support for the installed version. It has been lightly tested on both the portable and installed versions of PoB. It requires no additional file moving, manipulation, or otherwise. If you've butchered your PoB directory, I'd recommend doing a fresh install to make sure everything is as it should be.

**Comment by Eruyome** [comment]
Can't say that I made a thourough test but it works in general, thanks.
