### ISSUE TITLE
program suddenly returns all 0s for damage modifiers

### ISSUE THREAD

**Issue by tripleducky** [VolatilePulse/PoB-Item-Tester#8]
I was using this program to great effect yesterday. And it worked perfectly fine. Now when I hit Ctrl+Win+D and do a query I get all 0s for my dps weight values. Perhaps PoB updated itself and I didn't notice? The only other thing I did is restart my computer

**Comment by coldino** [comment]
Good catch!

This is due to a change on the DPS website. I've just pushed a fix which should sort it out again.

**Comment by tripleducky** [comment]
worked ty.
